server:
  port: 8090

#logging:
#  level:
#    root: DEBUG

# datasource
spring:
  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://localhost:5430/dbcom
    username: arthur
    password: 1q2w3e4r
    driver-class-name: org.postgresql.Driver

# jsp
spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp

---
spring.config.activate.on-profile: docker

app:
   client-server:
      host: client-server
      port: 8080
   resource-server:
      host: resource-server
      port: 8081