server:
  port: 8090

# datasource
spring:
  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://localhost:5432/postgres
    username: arthur
    password: 1q2w3e4r
    driver-class-name: org.postgresql.Driver

---
spring.config.activate.on-profile: docker

app:
   client-server:
      host: client-server
      port: 8080
   resource-server:
      host: resource-server
      port: 8081