CREATE TABLE USERS
(	USERNAME VARCHAR(50) NOT NULL,
     PASSWORD VARCHAR(68) NOT NULL,
     ENABLED SMALLINT NOT NULL,
     PRIMARY KEY(USERNAME)
);

INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES('employee','$2a$10$cRqfrdolNVFW6sAju0eNEOE0VC29aIyXwfsEsY2Fz2axy3MnH8ZGa',1);
INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES('manager','$2a$10$cRqfrdolNVFW6sAju0eNEOE0VC29aIyXwfsEsY2Fz2axy3MnH8ZGa',1);

CREATE TABLE AUTHORITIES
(		USERNAME VARCHAR(50) NOT NULL,
     AUTHORITY VARCHAR(68) NOT NULL,
     FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
);

INSERT INTO AUTHORITIES VALUES('employee','ROLE_EMPLOYEE');
INSERT INTO AUTHORITIES VALUES('employee','ROLE_USER');
INSERT INTO AUTHORITIES VALUES('manager','ROLE_MANAGER');
INSERT INTO AUTHORITIES VALUES('manager','ROLE_USER');